# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117Tni7okDwN5tvcSOo0pcccJZ9XoxrzT
"""

import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

transform = transforms.ToTensor()

train_dataset = torchvision.datasets.MNIST(root='./data', train=True, transform=transform, download=True)
test_dataset = torchvision.datasets.MNIST(root='./data', train=False, transform=transform)

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=64, shuffle=False)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

class RNNModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super().__init__()
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        x = x.squeeze(1)
        out, _ = self.rnn(x)
        out = out[:, -1, :]
        return self.fc(out)


class LSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super().__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, dropout=0.3)
        self.fc = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        x = x.squeeze(1)
        out, _ = self.lstm(x)
        out = out[:, -1, :]
        return self.fc(out)


class GRUModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super().__init__()
        self.gru = nn.GRU(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        x = x.squeeze(1)
        out, _ = self.gru(x)
        out = out[:, -1, :]
        return self.fc(out)


class BiLSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super().__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers,
                            batch_first=True, bidirectional=True)
        self.fc = nn.Linear(hidden_size * 2, num_classes)

    def forward(self, x):
        x = x.squeeze(1)
        out, _ = self.lstm(x)
        out = out[:, -1, :]
        return self.fc(out)

def train_model(model, epochs=10):
    model.to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    losses = []

    for epoch in range(epochs):
        total_loss = 0

        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        avg_loss = total_loss / len(train_loader)
        losses.append(avg_loss)
        print(f"Epoch {epoch+1}, Loss: {avg_loss}")

    return losses

def test_model(model):
    model.eval()
    correct, total = 0, 0

    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            _, predicted = torch.max(outputs, 1)

            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    return 100 * correct / total

input_size = 28
hidden_size = 128
num_layers = 1
num_classes = 10

# RNN
rnn = RNNModel(input_size, hidden_size, num_layers, num_classes)
rnn_loss = train_model(rnn)
rnn_acc = test_model(rnn)

# LSTM
lstm = LSTMModel(input_size, hidden_size, num_layers, num_classes)
lstm_loss = train_model(lstm)
lstm_acc = test_model(lstm)

# GRU
gru = GRUModel(input_size, hidden_size, num_layers, num_classes)
gru_loss = train_model(gru)
gru_acc = test_model(gru)

# BiLSTM
bilstm = BiLSTMModel(input_size, hidden_size, num_layers, num_classes)
bilstm_loss = train_model(bilstm)
bilstm_acc = test_model(bilstm)

print("RNN:", rnn_acc)
print("LSTM:", lstm_acc)
print("GRU:", gru_acc)
print("BiLSTM:", bilstm_acc)

plt.plot(rnn_loss, label="RNN")
plt.plot(lstm_loss, label="LSTM")
plt.plot(gru_loss, label="GRU")
plt.plot(bilstm_loss, label="BiLSTM")
plt.legend()
plt.title("Loss Comparison")
plt.show()

configs = [
    {"hidden_size": 64, "num_layers": 1},
    {"hidden_size": 128, "num_layers": 1},
    {"hidden_size": 128, "num_layers": 2},
]

results = []

for config in configs:
    print(f"\nTesting: {config}")

    model = LSTMModel(input_size, config["hidden_size"], config["num_layers"], num_classes)
    train_model(model, epochs=5)
    acc = test_model(model)

    results.append((config, acc))
    print(f"Accuracy: {acc}")

print("\n🔹 Hyperparameter Results")
for config, acc in results:
    print(f"Hidden: {config['hidden_size']}, Layers: {config['num_layers']} → Accuracy: {acc}")

from sklearn.metrics import confusion_matrix
import seaborn as sns

def plot_confusion(model):
    model.eval()
    preds, labels_list = [], []

    with torch.no_grad():
        for images, labels in test_loader:
            images = images.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs, 1)

            preds.extend(predicted.cpu().numpy())
            labels_list.extend(labels.numpy())

    cm = confusion_matrix(labels_list, preds)

    plt.figure()
    sns.heatmap(cm, annot=True, fmt='d')
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title("Confusion Matrix")
    plt.show()

plot_confusion(lstm)

"""##  Key Observations

- LSTM performs better than RNN due to handling vanishing gradient  
- GRU gives similar performance with faster training  
- BiLSTM improves accuracy using bidirectional context

##  Model Comparison

| Model | Accuracy | Remarks |
|------|--------|--------|
| RNN |  96.47%| Weak memory |
| LSTM |   98.79% | Best |
| GRU | 98.65% | Faster |
| BiLSTM | 98.68% | Best context |

##  Conclusion

RNN-based models were implemented for handwritten digit recognition.
LSTM and GRU significantly outperformed vanilla RNN.
BiLSTM provided further improvement using bidirectional learning.
Hyperparameter tuning improved model performance.

Overall, LSTM and BiLSTM achieved the best accuracy.
"""
